development:
  bucket: g5keg
  access_key_id: AKIAJU5UGVLFU77SIK3A
  secret_access_key: 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
test:
  bucket: g5keg
  access_key_id: AKIAJU5UGVLFU77SIK3A
  secret_access_key: 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
production:
  bucket: g5keg
  access_key_id: AKIAJU5UGVLFU77SIK3A
  secret_access_key: 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